// backend/config/swagger.js
import swaggerJsdoc from "swagger-jsdoc";
import swaggerUi from "swagger-ui-express";

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "BichoFull API",
      version: "1.0.0",
      description: "Documentação da API do sistema de apostas BichoFull",
    },
    servers: [
      {
        url: "http://localhost:3000/api",
      },
    ],
  },
  apis: ["./src/routes/*.js"], 
};

const specs = swaggerJsdoc(options);

export { swaggerUi, specs };
